# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: complex_calculator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'complex_calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63omplex_calculator.proto\x12\x11\x63omplexcalculator\"1\n\rComplexNumber\x12\x0c\n\x04real\x18\x01 \x01(\x01\x12\x12\n\nimaginaria\x18\x02 \x01(\x01\"C\n\x0f\x43omplexResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32 .complexcalculator.ComplexNumber\"\x8c\x01\n\x17\x43omplexOperationRequest\x12.\n\x04num1\x18\x01 \x01(\x0b\x32 .complexcalculator.ComplexNumber\x12.\n\x04num2\x18\x02 \x01(\x0b\x32 .complexcalculator.ComplexNumber\x12\x11\n\toperation\x18\x03 \x01(\t2p\n\x11\x43omplexCalculator\x12[\n\tCalculate\x12*.complexcalculator.ComplexOperationRequest\x1a\".complexcalculator.ComplexResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complex_calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLEXNUMBER']._serialized_start=47
  _globals['_COMPLEXNUMBER']._serialized_end=96
  _globals['_COMPLEXRESPONSE']._serialized_start=98
  _globals['_COMPLEXRESPONSE']._serialized_end=165
  _globals['_COMPLEXOPERATIONREQUEST']._serialized_start=168
  _globals['_COMPLEXOPERATIONREQUEST']._serialized_end=308
  _globals['_COMPLEXCALCULATOR']._serialized_start=310
  _globals['_COMPLEXCALCULATOR']._serialized_end=422
# @@protoc_insertion_point(module_scope)
